//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TaskManagerModel", "FK_Task_Category", "Category", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TaskManager.Database.Category), "Task", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TaskManager.Database.Task))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TaskManagerModel", "TaskResource", "Resource", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TaskManager.Database.Resource), "Task", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TaskManager.Database.Task))]

// Original file name:
// Generation date: 1/2/2010 12:54:53 AM
namespace TaskManager.Database
{
    
    /// <summary>
    /// There are no comments for TaskManagerEntities in the schema.
    /// </summary>
    public partial class TaskManagerEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new TaskManagerEntities object using the connection string found in the 'TaskManagerEntities' section of the application configuration file.
        /// </summary>
        public TaskManagerEntities() : 
                base("name=TaskManagerEntities", "TaskManagerEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TaskManagerEntities object.
        /// </summary>
        public TaskManagerEntities(string connectionString) : 
                base(connectionString, "TaskManagerEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TaskManagerEntities object.
        /// </summary>
        public TaskManagerEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "TaskManagerEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Category> Category
        {
            get
            {
                if ((this._Category == null))
                {
                    this._Category = base.CreateQuery<Category>("[Category]");
                }
                return this._Category;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Category> _Category;
        /// <summary>
        /// There are no comments for Resource in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Resource> Resource
        {
            get
            {
                if ((this._Resource == null))
                {
                    this._Resource = base.CreateQuery<Resource>("[Resource]");
                }
                return this._Resource;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Resource> _Resource;
        /// <summary>
        /// There are no comments for Task in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Task> Task
        {
            get
            {
                if ((this._Task == null))
                {
                    this._Task = base.CreateQuery<Task>("[Task]");
                }
                return this._Task;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Task> _Task;
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        public void AddToCategory(Category category)
        {
            base.AddObject("Category", category);
        }
        /// <summary>
        /// There are no comments for Resource in the schema.
        /// </summary>
        public void AddToResource(Resource resource)
        {
            base.AddObject("Resource", resource);
        }
        /// <summary>
        /// There are no comments for Task in the schema.
        /// </summary>
        public void AddToTask(Task task)
        {
            base.AddObject("Task", task);
        }
    }
    /// <summary>
    /// There are no comments for TaskManagerModel.Category in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TaskManagerModel", Name="Category")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Category : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryID">Initial value of CategoryID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Category CreateCategory(int categoryID, string name)
        {
            Category category = new Category();
            category.CategoryID = categoryID;
            category.Name = name;
            return category;
        }
        /// <summary>
        /// There are no comments for Property CategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                this.ReportPropertyChanging("CategoryID");
                this._CategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CategoryID");
                this.OnCategoryIDChanged();
            }
        }
        private int _CategoryID;
        partial void OnCategoryIDChanging(int value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Task in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TaskManagerModel", "FK_Task_Category", "Task")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Task> Task
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Task>("TaskManagerModel.FK_Task_Category", "Task");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Task>("TaskManagerModel.FK_Task_Category", "Task", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TaskManagerModel.Resource in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ResourceID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TaskManagerModel", Name="Resource")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Resource : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Resource object.
        /// </summary>
        /// <param name="resourceID">Initial value of ResourceID.</param>
        /// <param name="resourceName">Initial value of ResourceName.</param>
        /// <param name="emailAddress">Initial value of EmailAddress.</param>
        public static Resource CreateResource(int resourceID, string resourceName, string emailAddress)
        {
            Resource resource = new Resource();
            resource.ResourceID = resourceID;
            resource.ResourceName = resourceName;
            resource.EmailAddress = emailAddress;
            return resource;
        }
        /// <summary>
        /// There are no comments for Property ResourceID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ResourceID
        {
            get
            {
                return this._ResourceID;
            }
            set
            {
                this.OnResourceIDChanging(value);
                this.ReportPropertyChanging("ResourceID");
                this._ResourceID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ResourceID");
                this.OnResourceIDChanged();
            }
        }
        private int _ResourceID;
        partial void OnResourceIDChanging(int value);
        partial void OnResourceIDChanged();
        /// <summary>
        /// There are no comments for Property ResourceName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceName
        {
            get
            {
                return this._ResourceName;
            }
            set
            {
                this.OnResourceNameChanging(value);
                this.ReportPropertyChanging("ResourceName");
                this._ResourceName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ResourceName");
                this.OnResourceNameChanged();
            }
        }
        private string _ResourceName;
        partial void OnResourceNameChanging(string value);
        partial void OnResourceNameChanged();
        /// <summary>
        /// There are no comments for Property EmailAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this.OnEmailAddressChanging(value);
                this.ReportPropertyChanging("EmailAddress");
                this._EmailAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EmailAddress");
                this.OnEmailAddressChanged();
            }
        }
        private string _EmailAddress;
        partial void OnEmailAddressChanging(string value);
        partial void OnEmailAddressChanged();
        /// <summary>
        /// There are no comments for Property ResourceCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceCode
        {
            get
            {
                return this._ResourceCode;
            }
            set
            {
                this.OnResourceCodeChanging(value);
                this.ReportPropertyChanging("ResourceCode");
                this._ResourceCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ResourceCode");
                this.OnResourceCodeChanged();
            }
        }
        private string _ResourceCode;
        partial void OnResourceCodeChanging(string value);
        partial void OnResourceCodeChanged();
        /// <summary>
        /// There are no comments for Property ResourceDetail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceDetail
        {
            get
            {
                return this._ResourceDetail;
            }
            set
            {
                this.OnResourceDetailChanging(value);
                this.ReportPropertyChanging("ResourceDetail");
                this._ResourceDetail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ResourceDetail");
                this.OnResourceDetailChanged();
            }
        }
        private string _ResourceDetail;
        partial void OnResourceDetailChanging(string value);
        partial void OnResourceDetailChanged();
        /// <summary>
        /// There are no comments for Task in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TaskManagerModel", "TaskResource", "Task")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Task> Task
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Task>("TaskManagerModel.TaskResource", "Task");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Task>("TaskManagerModel.TaskResource", "Task", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TaskManagerModel.Task in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TaskID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TaskManagerModel", Name="Task")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Task : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Task object.
        /// </summary>
        /// <param name="taskID">Initial value of TaskID.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="duration">Initial value of Duration.</param>
        /// <param name="durationType">Initial value of DurationType.</param>
        /// <param name="startDate">Initial value of StartDate.</param>
        /// <param name="endDate">Initial value of EndDate.</param>
        /// <param name="percentComplete">Initial value of PercentComplete.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="priority">Initial value of Priority.</param>
        /// <param name="colorCategory">Initial value of ColorCategory.</param>
        /// <param name="flag">Initial value of Flag.</param>
        public static Task CreateTask(int taskID, string title, string description, int duration, string durationType, global::System.DateTime startDate, global::System.DateTime endDate, int percentComplete, string status, string priority, string colorCategory, string flag)
        {
            Task task = new Task();
            task.TaskID = taskID;
            task.Title = title;
            task.Description = description;
            task.Duration = duration;
            task.DurationType = durationType;
            task.StartDate = startDate;
            task.EndDate = endDate;
            task.PercentComplete = percentComplete;
            task.Status = status;
            task.Priority = priority;
            task.ColorCategory = colorCategory;
            task.Flag = flag;
            return task;
        }
        /// <summary>
        /// There are no comments for Property TaskID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskID
        {
            get
            {
                return this._TaskID;
            }
            set
            {
                this.OnTaskIDChanging(value);
                this.ReportPropertyChanging("TaskID");
                this._TaskID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaskID");
                this.OnTaskIDChanged();
            }
        }
        private int _TaskID;
        partial void OnTaskIDChanging(int value);
        partial void OnTaskIDChanged();
        /// <summary>
        /// There are no comments for Property ParentTaskID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ParentTaskID
        {
            get
            {
                return this._ParentTaskID;
            }
            set
            {
                this.OnParentTaskIDChanging(value);
                this.ReportPropertyChanging("ParentTaskID");
                this._ParentTaskID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentTaskID");
                this.OnParentTaskIDChanged();
            }
        }
        private global::System.Nullable<int> _ParentTaskID;
        partial void OnParentTaskIDChanging(global::System.Nullable<int> value);
        partial void OnParentTaskIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this.ReportPropertyChanging("Duration");
                this._Duration = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Duration");
                this.OnDurationChanged();
            }
        }
        private int _Duration;
        partial void OnDurationChanging(int value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Property DurationType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DurationType
        {
            get
            {
                return this._DurationType;
            }
            set
            {
                this.OnDurationTypeChanging(value);
                this.ReportPropertyChanging("DurationType");
                this._DurationType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("DurationType");
                this.OnDurationTypeChanged();
            }
        }
        private string _DurationType;
        partial void OnDurationTypeChanging(string value);
        partial void OnDurationTypeChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this.ReportPropertyChanging("StartDate");
                this._StartDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StartDate");
                this.OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Property EndDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this.OnEndDateChanging(value);
                this.ReportPropertyChanging("EndDate");
                this._EndDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EndDate");
                this.OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
        /// <summary>
        /// There are no comments for Property PercentComplete in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PercentComplete
        {
            get
            {
                return this._PercentComplete;
            }
            set
            {
                this.OnPercentCompleteChanging(value);
                this.ReportPropertyChanging("PercentComplete");
                this._PercentComplete = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PercentComplete");
                this.OnPercentCompleteChanged();
            }
        }
        private int _PercentComplete;
        partial void OnPercentCompleteChanging(int value);
        partial void OnPercentCompleteChanged();
        /// <summary>
        /// There are no comments for Property DueDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DueDate
        {
            get
            {
                return this._DueDate;
            }
            set
            {
                this.OnDueDateChanging(value);
                this.ReportPropertyChanging("DueDate");
                this._DueDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DueDate");
                this.OnDueDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DueDate;
        partial void OnDueDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDueDateChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Priority in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority
        {
            get
            {
                return this._Priority;
            }
            set
            {
                this.OnPriorityChanging(value);
                this.ReportPropertyChanging("Priority");
                this._Priority = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Priority");
                this.OnPriorityChanged();
            }
        }
        private string _Priority;
        partial void OnPriorityChanging(string value);
        partial void OnPriorityChanged();
        /// <summary>
        /// There are no comments for Property ColorCategory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorCategory
        {
            get
            {
                return this._ColorCategory;
            }
            set
            {
                this.OnColorCategoryChanging(value);
                this.ReportPropertyChanging("ColorCategory");
                this._ColorCategory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ColorCategory");
                this.OnColorCategoryChanged();
            }
        }
        private string _ColorCategory;
        partial void OnColorCategoryChanging(string value);
        partial void OnColorCategoryChanged();
        /// <summary>
        /// There are no comments for Property Flag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Flag
        {
            get
            {
                return this._Flag;
            }
            set
            {
                this.OnFlagChanging(value);
                this.ReportPropertyChanging("Flag");
                this._Flag = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Flag");
                this.OnFlagChanged();
            }
        }
        private string _Flag;
        partial void OnFlagChanging(string value);
        partial void OnFlagChanged();
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TaskManagerModel", "FK_Task_Category", "Category")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Category Category
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("TaskManagerModel.FK_Task_Category", "Category").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("TaskManagerModel.FK_Task_Category", "Category").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Category> CategoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("TaskManagerModel.FK_Task_Category", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Category>("TaskManagerModel.FK_Task_Category", "Category", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Resource in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TaskManagerModel", "TaskResource", "Resource")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Resource> Resource
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Resource>("TaskManagerModel.TaskResource", "Resource");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Resource>("TaskManagerModel.TaskResource", "Resource", value);
                }
            }
        }
    }
}
